### ISSUE TITLE
error index out of range

### ISSUE THREAD

**Issue by hakip** [omn0mn0m/Mion#28]
Almost all my challenge using the old code turn out like this:
Traceback (most recent call last):
File "/app/awc/utils.py", line 339, in parse_challenge_code
req_start_index = [i for i, s in enumerate(lines) if 'Legend' in s][0]
IndexError: list index out of range

**Comment by omn0mn0m** [comment]
Your post was missing the "Legend: [X] = Completed [O] = Not Completed" line in your challenge code. Unfortunately, I did not account for modifications from the default format due to there being seemingly a million ways to make a challenge post before.
