### ISSUE TITLE
Server Error (500) when attempting to edit challenges

### ISSUE THREAD

**Issue by CitizenElf** [omn0mn0m/Mion#8]
I'm encountering a server error when attempting to edit added challenges. It appears that the application is incorrectly assigning URLs for each challenge. The format should be 'https://anilist.co/forum/thread/00000/comment/00000' but the profile card section shows they are formatted as 'https://anilist.co/thread/00000/comment/0000'.
![profilecard example](https://user-images.githubusercontent.com/38828845/86216042-c3202480-bbc0-11ea-88a7-0ce8fbbea587.PNG)

**Comment by omn0mn0m** [comment]
Can you paste the forum Markdown code here so I can run it through the parser? I want to check if maybe some way that the July challenge code is formatted is throwing off how I parse.

**Comment by omn0mn0m** [comment]
Fixed the profile code showing the wrong url in [this commit](https://github.com/omn0mn0m/Mion/commit/7ac07b9b69b673a92324ed84c45d75ce3ee4d632)

**Comment by CitizenElf** [comment]
Sure thing, here's a copy of the markdown from my challenge post:
`# __July 2020 Challenge__

Challenge Start Date: 01/07
Challenge Finish Date: DD/MM
Legend: [X] = Completed [O] = Not Completed

1) [O] Start: DD/MM Finish: DD/MM __Watch an anime with the format “TV” and the tag “Cute Girls Doing Cute Things”__ [Kantai Collection: KanColle](https://anilist.co/anime/20553/)
2) [O] Start: DD/MM Finish: DD/MM __Watch an anime with the tag “Food”, “Maids” or “Iyashikei”__ [Konohana Kitan](https://anilist.co/anime/98506/)
3) [O] Start: DD/MM Finish: DD/MM __Watch an anime with a character that has pink hair__ [Wotaku ni Koi wa Muzukashii](https://anilist.co/anime/99578/) _[Narumi Momose](https://anilist.co/character/99578/)_
4) [O] Start: DD/MM Finish: DD/MM __Sugar Rush: Watch an anime with a scene where the character eats a delicious dessert__ [Blend S](https://anilist.co/anime/97994/) ~!Screenshot:img(https://imgur.com/00000.png)!~
5) [O] Start: DD/MM Finish: DD/MM __Watch an anime that has only female characters on its AniList cover__ [Yuru Camp△ OVA](https://anilist.co/anime/101206/)
6) [O] Start: DD/MM Finish: DD/MM __Watch an anime with a character that has a sweet tooth__ [Mahou Shoujo Madoka☆Magica: Hangyaku no Monogatari](https://anilist.co/anime/11981/)
7) [O] Start: DD/MM Finish: DD/MM __Summer Fun: Watch an anime in which the characters visit an amusement park, beach, swimming pool or traditional festival__ [Nakitai Watashi wa Neko wo Kaburu](https://anilist.co/anime/114963/) _Location: Matsuri, Episode: 01_
8) [O] Start: DD/MM Finish: DD/MM __Sweet Treat: Watch an anime with your highest rated genre and any of your top 3 highest rated tags__ [Kyochuu Rettou Movie](https://anilist.co/anime/107880/) ~!Screenshots:
img(https://i.imgur.com/et1Yznw.png)
img(https://i.imgur.com/MDcaF1a.png)!~
9) [O] Start: DD/MM Finish: DD/MM __Sharing is Caring: Watch an anime that started airing in any Summer season that another participant is watching for this challenge__ [Totsukuni no Shoujo](https://anilist.co/anime/108354/) _[Troy121’s Challenge Post](https://anilist.co/forum/thread/13948/comment/326303)_
10) [O] Start: DD/MM Finish: DD/MM __Cutie Pie: Watch an anime that features another participant's cutest character__ [Bakemonogatari](https://anilist.co/anime/5081/) _[Shinobu Oshino](https://anilist.co/character/23602/), [Emilylrhenderson09’s Challenge Post](https://anilist.co/forum/thread/13948/comment/326329/)_

~~~__Cutest Character:__ Share your cutest character!
[Bocchi Hitori](https://anilist.co/character/128986/)
img(https://steamuserimages-a.akamaihd.net/ugc/797611829250660154/2A6B9AA0304B6C6FB7CB3595124B096408EFC2F2/)~~~`

**Comment by omn0mn0m** [comment]
Looks like the issue is with the "Cutest Girl" section at the end. I'll need to rework things a bit to account for stuff like that.

**Comment by omn0mn0m** [comment]
Fixed. Challenges with extra info at the end should register correctly now. Also, if any general errors pop up while parsing, it won't return a server error. I'm still figuring out what I want to do about deleting bad challenge posts tho.

**Comment by omn0mn0m** [comment]
I ended up deciding not to have the delete button delete the comment on Anilist as well, in case some challenges are time sensitive.
